spring:
  config:
    import:
      - optional:classpath:.env[.properties]

  application:
    name: tecniservicios
    version: v1

  mvc:
    servlet:
      path: /

  profiles:
    active:
      - dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 240000
      idle-timeout: 200000
      connection-timeout: 30000
      validation-timeout: 5000
      minimum-idle: 5
      maximum-pool-size: 10
      keepalive-time: 30000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  image:
    path: c:\uploads\productos\

  servlet:
    multipart:
      max-file-size: 50MB

security:
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS

  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language

  public-routes:
    - /

  auth-entry-routes:
    - /auth/**

  admin-routes:
    - /dashboard/**

  protected-routes:
    - /dashboard/**

  no-admin-operation-to-self-routes:
    - methods:
        - PUT
      routes:
        - /user/{id:^(?!profile-image$).*$}
        - /user/{id}/email

  allowed-origins:
    - "*"

  allowed-credentials: false

  exposed-headers:
    - Content-Disposition

  jwt:
    secret: ${JWT_SECRET}

apiperu:
  base-url: ${API_PERU_URL:https://apiperu.dev/api}
  token: ${API_PERU_TOKEN:}
